Build fix: replace distribution method with fastlane hockey
StreetHawkSDK/ios pull request #100
Opened 2018-07-09 03:11 UTC by Xingyuj

Build fix: replace distribution method with fastlane hockey

2018-07-20 08:40 UTC, asyncmind0 requested changes

2018-07-20 08:40 UTC, jagguli commented on Example_DynamicFramework/Demo/Supporting Files/Demo-Info.plist
> +	<string>1532075099</string>
whats this ?

2018-07-20 08:40 UTC, jagguli commented on build.sh
> +#/usr/local/bin/puck -submit=auto -download=true -notes="$(git log -1)" -notes_type=markdown -source_path=$PWD -repository_url=https://github.com/StreetHawkSDK/ios -api_token=$HOCKEYAPP_TOKEN -app_id
why is this commented

2018-07-26 07:08 UTC, Xingyuj commented on Example_DynamicFramework/Demo/Supporting Files/Demo-Info.plist
> +	<string>1532075099</string>
bundle version

2018-07-26 08:21 UTC, asyncmind0 requested changes

2018-07-26 08:21 UTC, jagguli commented on Example_DynamicFramework/fastlane/Fastfile
> +        api_token: "b5adb4c23a934ac3807a8c9958a6daec",
pleas read this frm env variable HOCKEYAPP_TOKEN

2018-07-26 08:21 UTC, jagguli commented on Example_StaticLibrary/fastlane/Fastfile
> +        api_token: "b5adb4c23a934ac3807a8c9958a6daec",
pleas read this frm env variable HOCKEYAPP_TOKEN

2018-07-26 08:25 UTC, closed without merging